### ISSUE TITLE
VS code installation

### ISSUE THREAD

**Issue by MyVanitar** [Xpitfire/xtext-dnn#1]
Hi,

How can I install Xtext DNN as an extension in the VS Code? 

it seems that it was available before in the extensions list, but not now. 

I mean this: 

![vscodeplugin](https://cloud.githubusercontent.com/assets/18719591/25134048/c580bd04-2463-11e7-988f-e127f939389b.png)

**Comment by Xpitfire** [comment]
Hi, 

Thank you for the hint. I checked the marketplace and it really seems that it has been removed.
I will redeploy it today, so you can continue your exploration.

Best regards

**Comment by Xpitfire** [comment]
A new version is now available on the marketplace. Thank you again for the hint.
Best regards :)

**Comment by MyVanitar** [comment]
@Xpitfire 

Sorry but still I can not find it, even on the store.

![2017-04-19_0-31-04](https://cloud.githubusercontent.com/assets/18719591/25158383/49a74bee-24bd-11e7-8f0a-6a07b8f91fa0.jpg)

**Comment by Xpitfire** [comment]
https://marketplace.visualstudio.com/items?itemName=xpitfire.xtext-dnn

It is the second search result. The icon just changed.

**Comment by MyVanitar** [comment]
Previously it was Xtext VS Code DNN, but both text and icon have changed.

Does it work under windows also?

**Comment by Xpitfire** [comment]
I have tested it on Ubuntu 16.04 and Windows 10 and both for VS Code 1.11.2. It should work.

**Comment by MyVanitar** [comment]
Should I install any other dependencies also, or it is enough if it is installed alone?

**Comment by Xpitfire** [comment]
You should have Java 8 installed, but that alone should do the trick. Do you have any issues installing it?

**Comment by MyVanitar** [comment]
I was getting a general error in the past sometimes (not in the installation phase), but let me to try it now. How can I compile or deploy the code? I mean what should I do to generate the output codes/files?

**Comment by Xpitfire** [comment]
- Create a new file ending with *.dls
- Copy the VS Code example in it and you should get a new directory, somthing like "src-gen" where the *.prototxt, etc. are included / or take the example below
- For more details see the [Documentation](https://github.com/Xpitfire/xtext-dnn/tree/master/doc)
- have fun :)

```
network "DemoNet" {
	epochs = 10
	batchSize = 50
	imageSize = 32
    imageChannels = 3
    outputLabels = 10

	caffePath = "$CAFFE_HOME"
    outputPath = "/media/xpitfire/data/temp"	

	updater -> sgd
	learningRate = 0.003

	conv   (name:"conv1"   in:data    out:128) { kernelSize = 5 }
	conv   (name:"conv2"              out:128) { kernelSize = 5 }
	branch (name:"branch1" in:"conv2" out:128) {
		eltwiseOperation -> PROD
		conv   (name:"branch_conv1"                 out:128)  { kernelSize = 1 }
		branch (name:"subbranch1" in:"branch_conv1" out:128)  {
			eltwiseOperation -> PROD
			conv (name:"subbranch_conv1" in:"branch_conv1" out:128) { kernelSize = 1 }
			norm (name:"norm1") { useGlobalStats = true }
			scale (name:"scale1") { useBiasTerm = true }
		}
	}
	pool   (name:"pool1"              out:2)  { type -> MAX, stride = 1 }
	conv   (name:"conv3"              out:64) { kernelSize = 3 }
	branch (name:"branch2" in:"conv3" out:64) {
		eltwiseOperation -> SUM
		conv (name:"branch_conv2" in:"conv3" out:64) { kernelSize = 1 }
		norm (name:"norm2") { useGlobalStats = true }
		scale (name:"scale2") { useBiasTerm = true }
	}
		
	pool   (name:"pool2"  out:2)  { type -> MAX, stride = 1 }
	conv   (name:"conv4"  out:32) { kernelSize = 3 }
	conv   (name:"cconv5" out:16) { kernelSize = 3 }
	dense  (name:"dense1" out:64)

	dense [(name:"test" out:256), (name:"test2" out:256)]
	dense  (name:finalLayer out:labels) { biasInit -> xavier }

}
```

**Comment by Xpitfire** [comment]
BTW thanks for trying it out 👍 
I really appreciate it :)

**Comment by MyVanitar** [comment]
@Xpitfire 

Your work is very precious and appreciated. it reduces the design/coding time dramatically.

I get this error. Please have a look. Windows 10. 

![2017-04-19_9-04-52](https://cloud.githubusercontent.com/assets/18719591/25172074/2bd12aac-2505-11e7-95c9-38efcbdfa105.jpg)

**Comment by Xpitfire** [comment]
I will analyse this tonight and try to fix it. 
I already opend an issue for this.

In the meanwhile try to checkout the code from GitHub and build and deploy manually:

Prerequisites:
- NodeJS
- Java 8
- Gradle

Uninstall any previously installed DNN extensions from VS Code.
Execute:
```
./gradlew startCode
```
This should resolve all dependencies and for me this worked perfectly also on Windows 10.

![image](https://cloud.githubusercontent.com/assets/7037963/25172596/cf7fc85c-24f1-11e7-8a8f-d2d7e9d3fc19.png)

**Comment by MyVanitar** [comment]
> Uninstall any previously installed DNN extensions from VS Code.
Execute:
./gradlew startCode

It seems to be a Linux command, where should I run it actually?
The path of the dependencies matter?

Sorry for many questions.

**Comment by Xpitfire** [comment]
I recommand to use PowerShell. If everything is set up properly you can use the command above.

What I meant is that you should manually uninstall all other DNN extensions (if you still have any):
![image](https://cloud.githubusercontent.com/assets/7037963/25173212/8ce8b9ca-24f3-11e7-80fe-24ba6650ba25.png)

And then run the install command ``` ./gradlew startCode ``` after setting up NodeJS, Java 8 and Gradle. If you are not familiar with setting up the environment its also no issue.

Maybe try first to install the extension manually from the release page on GitHub:
- [Download](https://github.com/Xpitfire/xtext-dnn/releases) the extension
![image](https://cloud.githubusercontent.com/assets/7037963/25173465/797c5a08-24f4-11e7-8a9a-c61cd47ea823.png)
- Manually uninstall previous versions
- Manually install new version: 
![image](https://cloud.githubusercontent.com/assets/7037963/25173439/61f3d8ac-24f4-11e7-81a4-ddc9393e9a51.png)

**Comment by MyVanitar** [comment]
> Maybe try first to install the extension manually from the release page on GitHub:

I got the same errors. it made no difference. I will try the manual mode.

**Comment by Xpitfire** [comment]
Maybe this helps you out:
- [Grade install guid](https://gradle.org/install)
- [NodeJS](https://nodejs.org/de/download/)
- [JDK 8](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)

Sorry for the trouble!

**Comment by MyVanitar** [comment]
@Xpitfire 

Have you fixed the issue?

Besides I've installed all dependencies, but when I run the command `gradlew startCode`, it begins to download an older version of the Gradle, where should I change to fix it?

![2017-04-20_12-29-56](https://cloud.githubusercontent.com/assets/18719591/25219917/5095dffc-25c5-11e7-92c6-060d45b71a77.jpg)

**Comment by MyVanitar** [comment]
@Xpitfire 

Alright, I downloaded the VS Code extension few moments ago and I saw the issue has been solved and files are generated. Good Job. The issue is solved now.

1) The only thing remains I appreciate if you make an example to run a model from creation to train it by DIGITS as one image shows it. https://github.com/Xpitfire/xtext-dnn/tree/master/doc

2) Besides, the sources to teach the syntax to build a model.

3) Does this code used to make classifiers? what about object detection or semantic segmentation tasks?

4) Can we make FCN or RCNN networks also?

**Comment by Xpitfire** [comment]
Hi @VanitarNordic 
I am glad to hear that the extension is working 👍 

Now to your questions:
1 & 2) Do you mean something like:
* Open a new Folder with VS Code
* Create a new file with the extions *.dls => example.dls
* The file has to contain of:
``` network <name-of-network> { ... } ```
This represents a new network model.
* Add the first attribute:
```
network "Example" { 
    epochs = 100 // this indicates that there will be 100 iterations
    ...
} 
```
* ...
* The generated output will be available in the src-gen directories 

3 & 4) The extension was specified and used to make classifiers. This project was initiated due to related work, which happens to be my master thesis. It helped me out with prototyping network architectures and there is still a lot missing to completely cover the Caffe Script *.prototxt features offered by NVIDIA.

If you are interested I can offer you to contribute to the project and we can extend the features together.

**Comment by MyVanitar** [comment]
What is the network syntax?, it seems it is like the torch framework syntax.
then it might work if we write an FCN also because in that case your code reshape it, doesn't matter what is written as the model code.
 very good job as a mater thesis. it worthes even PHD.
